from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from humanoid_training import hardware
from humanoid_training.adapters.base import EnginePayload, EvalResult, LogFn, Support
from humanoid_training.adapters.common import ignored_scene_fields, recipe_adapter_config
from humanoid_training.adapters.process import harvest_mp4, stream_process, write_job
from humanoid_training.errors import AdapterUnavailable

ISAAC_G1_FLAT = "Isaac-Velocity-Flat-G1-v0"
DEFAULT_IMAGE = "nvcr.io/nvidia/isaac-lab:2.2.0"
LOGDIR_NAME = "isaac_logs"


def _task_image(spec: dict[str, Any], payload: EnginePayload | None = None) -> tuple[str, str]:
    cfg = recipe_adapter_config(spec, "isaaclab")
    extra = (payload.extra if payload else {}) or {}
    task = str((payload.env_name if payload else None) or cfg.get("task") or ISAAC_G1_FLAT)
    image = str(cfg.get("image") or extra.get("image") or DEFAULT_IMAGE)
    return task, image


def isaac_train_play_commands(task: str, cli: str, *, want_video: bool) -> tuple[list[str], list[str]]:
    train = [cli, "-p", "scripts/reinforcement_learning/rsl_rl/train.py", "--task", task, "--headless"]
    play = [cli, "-p", "scripts/reinforcement_learning/rsl_rl/play.py", "--task", task, "--headless"]
    if want_video:
        train.append("--video")
        play.extend(["--video", "--video_length", "200"])
    return train, play


class IsaacLabAdapter:
    """Compile an OSMO workflow. Launch via isaaclab.sh or GPU Docker; else block."""

    name = "isaaclab"

    def support(self, spec: dict[str, Any]) -> Support:
        cfg = recipe_adapter_config(spec, self.name)
        if cfg.get("unsupported"):
            return Support(False, str(cfg["unsupported"]))
        if not cfg.get("task"):
            return Support(False, "recipe does not define adapters.isaaclab.task")
        return Support(True)

    def compile(self, spec: dict[str, Any]) -> EnginePayload:
        task, image = _task_image(spec)
        name = spec.get("name") or "isaac-job"
        want_video = bool((spec.get("eval") or {}).get("record_video", True))
        video_train = " --video" if want_video else ""
        video_play = " --video --video_length 200" if want_video else ""
        workflow = f"""\
# Generated by Humanoid Training. Submit with: osmo workflow submit osmo_workflow.yaml
# See https://nvidia.github.io/OSMO/main/user_guide/workflows/submission.html
# Local GPU alternative: docker run --gpus all {image}
workflow:
  name: {name}
  tasks:
    - name: train
      image: {image}
      environment:
        ACCEPT_EULA: "Y"
        NO_NUCLEUS: "Y"
      command: ["bash"]
      args: ["/tmp/entry.sh"]
      files:
        - path: /tmp/entry.sh
          contents: |
            set -euo pipefail
            ./isaaclab.sh -p scripts/reinforcement_learning/rsl_rl/train.py \\
              --task {task} --headless{video_train}
            ./isaaclab.sh -p scripts/reinforcement_learning/rsl_rl/play.py \\
              --task {task} --headless{video_play}
"""
        train_sh = "\n".join(
            [
                "#!/usr/bin/env bash",
                "set -euo pipefail",
                "# Generated by Humanoid Training. Run inside Isaac Lab (or the NGC image).",
                f"# task={task}",
                f'./isaaclab.sh -p scripts/reinforcement_learning/rsl_rl/train.py --task {task} --headless{video_train}',
                f'./isaaclab.sh -p scripts/reinforcement_learning/rsl_rl/play.py --task {task} --headless{video_play}',
                "# When this script runs in GPU Docker, copy clips into the mounted run dir.",
                "if [ -d /ht_run ]; then",
                "  mkdir -p /ht_run/isaac_logs",
                "  find . -name '*.mp4' -type f -exec cp -n {} /ht_run/isaac_logs/ \\; || true",
                "fi",
                "",
            ]
        )
        train_cmd = [
            "./isaaclab.sh",
            "-p",
            "scripts/reinforcement_learning/rsl_rl/train.py",
            "--task",
            task,
            "--headless",
        ]
        if want_video:
            train_cmd.append("--video")
        payload = EnginePayload(
            adapter=self.name,
            env_name=task,
            command=train_cmd,
            ignored_fields=ignored_scene_fields(spec, honors_scene=False),
            notes=[
                "Isaac Lab GPU training. launch() uses isaaclab.sh or GPU Docker.",
                f"Task id: {task}",
                "Or: osmo workflow submit osmo_workflow.yaml (submit only; no remote harvest).",
            ],
            extra={"task": task, "image": image},
        )
        payload.files["engine_payload.json"] = json.dumps(payload.as_dict(), indent=2)
        payload.files["osmo_workflow.yaml"] = workflow
        payload.files["train_isaac.sh"] = train_sh
        return payload

    def launch(
        self,
        spec: dict[str, Any],
        payload: EnginePayload,
        run_dir: Path,
        log: LogFn,
    ) -> EvalResult:
        run_dir = Path(run_dir)
        task, image = _task_image(spec, payload)
        want_video = bool((spec.get("eval") or {}).get("record_video", True))
        logdir = run_dir / LOGDIR_NAME
        logdir.mkdir(parents=True, exist_ok=True)

        cli = hardware.isaac_cli()
        if cli and hardware.gpu_available():
            return self._launch_local(spec, run_dir, log, task, cli, logdir, want_video)

        if hardware.isaac_launch_ready() and hardware.docker_bin():
            return self._launch_docker(spec, run_dir, log, task, image, logdir, want_video)

        osmo = hardware.osmo_cli()
        yaml_path = run_dir / "osmo_workflow.yaml"
        if osmo and yaml_path.is_file():
            submit = [osmo, "workflow", "submit", str(yaml_path)]
            log(" ".join(submit))
            write_job(run_dir, {"command": submit, "status": "submitting", "launch": "osmo"})
            rc = stream_process(
                submit,
                run_dir,
                log,
                missing="osmo CLI could not be started",
            )
            write_job(
                run_dir,
                {"command": submit, "returncode": rc, "status": "submitted", "launch": "osmo"},
            )
            raise AdapterUnavailable(
                f"osmo workflow submit exited {rc}. "
                "This phase does not harvest a remote OSMO video — not a silent Isaac success. "
                "On a local GPU: set HT_ISAAC_CLI to isaaclab.sh, or "
                "HT_DOCKER_GPU=1 and docker run the NGC Isaac Lab image. "
                "Or use g1-stand / pick-and-place on the CPU studio. "
                f"Workflow file: {yaml_path}"
            )

        raise AdapterUnavailable(
            "Isaac Lab execution is blocked on this machine — not a silent failure. "
            "On a GPU box with Isaac Lab:\n"
            "  ./isaaclab.sh -p scripts/reinforcement_learning/rsl_rl/train.py "
            f"--task {task} --headless --video\n"
            "Or submit the compiled OSMO file:\n"
            "  osmo workflow submit osmo_workflow.yaml\n"
            "Or GPU Docker:\n"
            f"  HT_DOCKER_GPU=1 docker run --gpus all {image}\n"
            "Do not use ht train --docker (that is the Phase 1 CPU image). "
            "Or use g1-stand / pick-and-place on the CPU studio. "
            f"Compiled payload: {run_dir}"
        )

    def _finish(
        self,
        spec: dict[str, Any],
        run_dir: Path,
        log: LogFn,
        *,
        task: str,
        logdir: Path,
        want_video: bool,
        rc: int,
        runner: str,
    ) -> EvalResult:
        facts: dict[str, Any] = {
            "kind": "rl",
            "engine": "isaaclab",
            "device": "gpu",
            "env": task,
            "policy": "ppo",
            "returncode": rc,
            "launch": runner,
        }
        if rc != 0:
            return EvalResult(
                success_rate=0.0,
                mean_return=0.0,
                episodes=int((spec.get("eval") or {}).get("episodes") or 0),
                video_path=None,
                passed=False,
                notes=[f"Isaac Lab exited {rc}. Not substituting a stand clip."],
                facts=facts,
            )
        dest = run_dir / "eval.mp4"
        video = harvest_mp4(logdir, dest) if want_video else None
        if want_video and video is None:
            # Train/play write logs/rsl_rl relative to cwd (run_dir).
            video = harvest_mp4(run_dir, dest)
        if want_video and video is None:
            raise AdapterUnavailable(
                "Isaac Lab finished (exit 0) but wrote no *.mp4. "
                "Not substituting a stand clip. "
                f"Run dir: {run_dir}"
            )
        notes = [
            f"Isaac Lab task={task} launch={runner}",
            "Eval clip is the engine rollout, not an independent reach/upright score.",
        ]
        if video:
            notes.append(f"harvested {video.name}")
            log(f"harvested {video}")
        return EvalResult(
            success_rate=1.0,
            mean_return=0.0,
            episodes=int((spec.get("eval") or {}).get("episodes") or 1),
            video_path=video,
            passed=True,
            notes=notes,
            facts=facts,
        )

    def _launch_local(
        self,
        spec: dict[str, Any],
        run_dir: Path,
        log: LogFn,
        task: str,
        cli: str,
        logdir: Path,
        want_video: bool,
    ) -> EvalResult:
        train, play = isaac_train_play_commands(task, cli, want_video=want_video)
        log(" ".join(train))
        write_job(run_dir, {"command": train, "status": "starting", "launch": "isaaclab.sh"})
        rc = stream_process(train, run_dir, log, missing="Could not start isaaclab.sh")
        if rc == 0:
            log(" ".join(play))
            rc_play = stream_process(play, run_dir, log, missing="Could not start isaaclab.sh play")
            if rc_play != 0:
                rc = rc_play
        write_job(run_dir, {"command": train + play, "returncode": rc, "status": "exited", "launch": "isaaclab.sh"})
        return self._finish(
            spec, run_dir, log, task=task, logdir=logdir, want_video=want_video, rc=rc, runner="isaaclab.sh"
        )

    def _launch_docker(
        self,
        spec: dict[str, Any],
        run_dir: Path,
        log: LogFn,
        task: str,
        image: str,
        logdir: Path,
        want_video: bool,
    ) -> EvalResult:
        docker = hardware.docker_bin()
        if not docker:
            raise AdapterUnavailable("Docker is not on PATH for Isaac GPU launch.")
        script = run_dir / "train_isaac.sh"
        if not script.is_file():
            raise AdapterUnavailable(
                "train_isaac.sh is missing from the run dir; compile the Isaac payload first. "
                f"Run dir: {run_dir}"
            )
        cmd = [
            docker,
            "run",
            "--rm",
            "--gpus",
            "all",
            "-v",
            f"{run_dir}:/ht_run",
            "-e",
            "ACCEPT_EULA=Y",
            "-e",
            "NO_NUCLEUS=Y",
            image,
            "bash",
            "/ht_run/train_isaac.sh",
        ]
        log(" ".join(cmd))
        write_job(run_dir, {"command": cmd, "image": image, "status": "starting", "launch": "docker"})
        rc = stream_process(cmd, run_dir, log, missing="Could not start docker for Isaac Lab")
        write_job(
            run_dir,
            {"command": cmd, "image": image, "returncode": rc, "status": "exited", "launch": "docker"},
        )
        return self._finish(
            spec, run_dir, log, task=task, logdir=logdir, want_video=want_video, rc=rc, runner="docker"
        )
