from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from humanoid_training.adapters.base import EnginePayload, EvalResult, LogFn, Support
from humanoid_training.adapters.common import ignored_scene_fields, recipe_adapter_config
from humanoid_training.errors import AdapterUnavailable


ISAAC_G1_FLAT = "Isaac-Velocity-Flat-G1-v0"


class IsaacLabAdapter:
    """Compile an OSMO-style workflow. Does not launch Isaac Sim in Phase 0."""

    name = "isaaclab"

    def support(self, spec: dict[str, Any]) -> Support:
        cfg = recipe_adapter_config(spec, self.name)
        if cfg.get("unsupported"):
            return Support(False, str(cfg["unsupported"]))
        if not cfg.get("task"):
            return Support(False, "recipe does not define adapters.isaaclab.task")
        return Support(True)

    def compile(self, spec: dict[str, Any]) -> EnginePayload:
        cfg = recipe_adapter_config(spec, self.name)
        task = str(cfg.get("task") or ISAAC_G1_FLAT)
        image = str(cfg.get("image") or "nvcr.io/nvidia/isaac-lab:2.2.0")
        name = spec.get("name") or "isaac-job"
        workflow = f"""\
# Generated by Humanoid Training. Submit with OSMO or run inside the Isaac Lab container.
# See https://developer.nvidia.com/osmo
workflow:
  name: {name}
  tasks:
    - name: train
      image: {image}
      environment:
        ACCEPT_EULA: "Y"
        NO_NUCLEUS: "Y"
      command: ["bash"]
      args: ["/tmp/entry.sh"]
      files:
        - path: /tmp/entry.sh
          contents: |
            set -euo pipefail
            ./isaaclab.sh -p scripts/reinforcement_learning/rsl_rl/train.py \\
              --task {task} --headless
            ./isaaclab.sh -p scripts/reinforcement_learning/rsl_rl/play.py \\
              --task {task} --headless --video --video_length 200
"""
        payload = EnginePayload(
            adapter=self.name,
            env_name=task,
            command=[
                "./isaaclab.sh",
                "-p",
                "scripts/reinforcement_learning/rsl_rl/train.py",
                "--task",
                task,
                "--headless",
            ],
            ignored_fields=ignored_scene_fields(spec, honors_scene=False),
            notes=[
                "Isaac Lab GPU training. Phase 3 will submit this workflow.",
                f"Task id: {task}",
            ],
            extra={"task": task, "image": image},
        )
        payload.files["engine_payload.json"] = json.dumps(payload.as_dict(), indent=2)
        payload.files["osmo_workflow.yaml"] = workflow
        return payload

    def launch(
        self,
        spec: dict[str, Any],
        payload: EnginePayload,
        run_dir: Path,
        log: LogFn,
    ) -> EvalResult:
        log("Isaac Lab launch is not enabled in this phase")
        raise AdapterUnavailable(
            "Isaac Lab execution is Phase 3. This run compiled an OSMO workflow "
            f"to {run_dir / 'osmo_workflow.yaml'}. Submit that on a cluster, or "
            "install Isaac Lab and run the command in engine_payload.json."
        )
