from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from humanoid_training import hardware
from humanoid_training.adapters.base import EnginePayload, EvalResult, LogFn, Support
from humanoid_training.adapters.common import ignored_scene_fields, recipe_adapter_config
from humanoid_training.adapters.process import harvest_mp4, stream_process, write_job
from humanoid_training.errors import AdapterUnavailable

LOGDIR_NAME = "lerobot_logs"


def _policy(spec: dict[str, Any], payload: EnginePayload | None = None) -> str:
    cfg = recipe_adapter_config(spec, "lerobot")
    extra = (payload.extra if payload else {}) or {}
    return str(
        extra.get("policy")
        or cfg.get("policy")
        or (spec.get("train") or {}).get("policy")
        or "act"
    )


def _dataset_root(spec: dict[str, Any], run_dir: Path | None = None) -> str:
    datasets = list((spec.get("data") or {}).get("datasets") or [])
    if datasets:
        return str(datasets[0])
    if run_dir is not None:
        return str(Path(run_dir) / "lerobot_dataset")
    return ""


def lerobot_train_command(
    spec: dict[str, Any],
    *,
    payload: EnginePayload | None = None,
    dataset: str = "",
    output_dir: str | Path = LOGDIR_NAME,
) -> list[str]:
    policy = _policy(spec, payload)
    steps = int((spec.get("train") or {}).get("steps") or 1000)
    seed = int((spec.get("train") or {}).get("seed") or 1)
    dataset = dataset or _dataset_root(spec)
    # Modern CLI: lerobot-train --policy.type=act --dataset.root=...
    # Fake file CLIs accept the same flags for tests.
    extra = [
        f"--policy.type={policy}",
        "--policy.device=cuda",
        f"--dataset.root={dataset}",
        "--dataset.repo_id=local/pick-and-place",
        f"--output_dir={output_dir}",
        f"--steps={steps}",
        f"--seed={seed}",
        "--wandb.enable=false",
        "--batch_size=8",
    ]
    return hardware.lerobot_train_argv(extra)


class LeRobotAdapter:
    """Compile and, when lerobot + GPU are present, launch ACT on local demos."""

    name = "lerobot"

    def support(self, spec: dict[str, Any]) -> Support:
        cfg = recipe_adapter_config(spec, self.name)
        if cfg.get("unsupported"):
            return Support(False, str(cfg["unsupported"]))
        method = str((spec.get("train") or {}).get("method") or "")
        if method and method != "imitation":
            return Support(False, "lerobot adapter is for imitation jobs")
        return Support(True)

    def compile(self, spec: dict[str, Any]) -> EnginePayload:
        policy = _policy(spec)
        dataset = _dataset_root(spec) or "lerobot_dataset"
        command = lerobot_train_command(spec, dataset=dataset, output_dir=LOGDIR_NAME)
        # Portable script uses lerobot-train even if this host resolved a fake file CLI.
        portable = [
            "lerobot-train",
            f"--policy.type={policy}",
            "--policy.device=cuda",
            f"--dataset.root={dataset}",
            "--dataset.repo_id=local/pick-and-place",
            f"--output_dir={LOGDIR_NAME}",
            f"--steps={int((spec.get('train') or {}).get('steps') or 1000)}",
            "--wandb.enable=false",
        ]
        script = "\n".join(
            [
                "#!/usr/bin/env bash",
                "set -euo pipefail",
                "# Generated by Humanoid Training. Requires: pip install 'lerobot[training]' + NVIDIA GPU",
                f"# policy={policy} dataset={dataset}",
                "if ! command -v lerobot-train >/dev/null 2>&1 && ! python -c 'import lerobot' >/dev/null 2>&1; then",
                '  echo "LeRobot is not installed. pip install \'lerobot[training]\'" >&2',
                "  exit 12",
                "fi",
                "exec " + " ".join(portable),
                "",
            ]
        )
        payload = EnginePayload(
            adapter=self.name,
            env_name=policy,
            command=command,
            ignored_fields=ignored_scene_fields(spec, honors_scene=False),
            notes=[
                "LeRobot ACT on the same local demos as CPU linear-BC.",
                "launch() runs when lerobot + GPU are present; otherwise use mujoco.",
                "Not finger grasping.",
            ],
            extra={"policy": policy, "dataset": dataset, "logdir": LOGDIR_NAME},
        )
        payload.files["engine_payload.json"] = json.dumps(payload.as_dict(), indent=2)
        payload.files["train_lerobot.sh"] = script
        return payload

    def launch(
        self,
        spec: dict[str, Any],
        payload: EnginePayload,
        run_dir: Path,
        log: LogFn,
    ) -> EvalResult:
        run_dir = Path(run_dir)
        log("checking for LeRobot ACT")
        if not hardware.lerobot_cli():
            raise AdapterUnavailable(
                "LeRobot is not installed on this machine. "
                "CPU imitation still works: pick-and-place on mujoco (linear-BC). "
                "On a GPU box: pip install 'lerobot[training]', then Train again. "
                f"Compiled payload: {run_dir}"
            )
        if not hardware.gpu_available():
            raise AdapterUnavailable(
                "ACT train is blocked: no NVIDIA GPU. "
                "Use pick-and-place on mujoco for CPU linear-BC. "
                f"Compiled payload: {run_dir}"
            )

        data_dir = self._ensure_dataset(spec, run_dir, log)
        logdir = run_dir / LOGDIR_NAME
        logdir.mkdir(parents=True, exist_ok=True)
        policy = _policy(spec, payload)
        steps = int((spec.get("train") or {}).get("steps") or 1000)
        seed = int((spec.get("train") or {}).get("seed") or 1)
        want_video = bool((spec.get("eval") or {}).get("record_video", True))
        command = lerobot_train_command(
            spec, payload=payload, dataset=str(data_dir), output_dir=logdir
        )
        log(" ".join(command))
        write_job(
            run_dir,
            {
                "command": command,
                "dataset": str(data_dir),
                "policy": policy,
                "status": "starting",
            },
        )
        rc = stream_process(
            command,
            run_dir,
            log,
            missing="Could not start lerobot-train. pip install 'lerobot[training]'",
        )
        write_job(
            run_dir,
            {
                "command": command,
                "dataset": str(data_dir),
                "policy": policy,
                "returncode": rc,
                "status": "exited",
            },
        )
        facts: dict[str, Any] = {
            "kind": "imitation",
            "policy": policy,
            "engine": "lerobot",
            "device": "gpu",
            "seed": seed,
            "steps": steps,
            "dataset": str(data_dir),
            "returncode": rc,
        }
        if rc != 0:
            log(f"lerobot-train exited {rc}; not claiming ACT success")
            return EvalResult(
                success_rate=0.0,
                mean_return=0.0,
                episodes=int((spec.get("eval") or {}).get("episodes") or 0),
                video_path=None,
                passed=False,
                notes=[
                    f"LeRobot ACT exited {rc}. Not substituting linear-BC mustard.",
                    "Not finger grasping.",
                ],
                facts=facts,
            )
        dest = run_dir / "eval.mp4"
        video = harvest_mp4(logdir, dest) if want_video else None
        if want_video and video is None:
            raise AdapterUnavailable(
                "LeRobot ACT finished (exit 0) but wrote no *.mp4 under "
                f"{logdir}. Not substituting a linear-BC clip. Run dir: {run_dir}"
            )
        notes = [
            f"LeRobot ACT policy={policy} steps={steps} seed={seed}",
            "Same local demos as CPU linear-BC. Not finger grasping.",
        ]
        if video:
            notes.append(f"harvested {video.name} from lerobot_logs")
            log(f"harvested {video}")
        else:
            notes.append("record_video=false; no eval.mp4")
        return EvalResult(
            success_rate=1.0,
            mean_return=0.0,
            episodes=int((spec.get("eval") or {}).get("episodes") or 1),
            video_path=video,
            passed=True,
            notes=notes,
            facts=facts,
        )

    def _ensure_dataset(self, spec: dict[str, Any], run_dir: Path, log: LogFn) -> Path:
        datasets = list((spec.get("data") or {}).get("datasets") or [])
        if datasets:
            path = Path(datasets[0])
            if not (path / "meta" / "info.json").is_file():
                raise AdapterUnavailable(
                    f"LeRobot dataset missing meta/info.json: {path}. "
                    "Inspect in the Data room, or clear data.datasets to auto-script demos."
                )
            return path
        from humanoid_training.demos import record_scripted_pick_place

        data_dir = run_dir / "lerobot_dataset"
        n_ep = int((spec.get("data") or {}).get("min_episodes") or 4)
        n_ep = max(2, min(n_ep, 8))
        log(f"recording {n_ep} scripted demos for ACT → {data_dir}")
        record_scripted_pick_place(
            spec,
            data_dir,
            episodes=n_ep,
            include_failure=True,
            seed=int((spec.get("train") or {}).get("seed") or 1),
        )
        return data_dir
