from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from humanoid_training.adapters.base import EnginePayload, EvalResult, LogFn, Support
from humanoid_training.adapters.common import ignored_scene_fields, recipe_adapter_config
from humanoid_training.errors import AdapterUnavailable


class LeRobotAdapter:
    """Imitation / dataset path. Compile a train command; launch is Phase 2."""

    name = "lerobot"

    def support(self, spec: dict[str, Any]) -> Support:
        cfg = recipe_adapter_config(spec, self.name)
        if cfg.get("unsupported"):
            return Support(False, str(cfg["unsupported"]))
        datasets = list((spec.get("data") or {}).get("datasets") or [])
        if not datasets:
            return Support(
                False,
                "LeRobot imitation needs data.datasets (a folder with meta/info.json). "
                "Inspect datasets in the Data room. CPU scene preview uses mujoco.",
            )
        return Support(
            False,
            "LeRobot training (ACT / similar) is Phase 2. The Data room can inspect "
            "a local LeRobot dataset; this adapter will launch once lerobot is wired.",
        )

    def compile(self, spec: dict[str, Any]) -> EnginePayload:
        cfg = recipe_adapter_config(spec, self.name)
        policy = str(cfg.get("policy") or (spec.get("train") or {}).get("policy") or "act")
        datasets = list((spec.get("data") or {}).get("datasets") or [])
        dataset = datasets[0] if datasets else ""
        script = "\n".join(
            [
                "#!/usr/bin/env bash",
                "set -euo pipefail",
                "# Generated by Humanoid Training. Requires: pip install lerobot",
                f"# policy={policy} dataset={dataset}",
                "if ! python -c 'import lerobot' >/dev/null 2>&1; then",
                '  echo "LeRobot is not installed. pip install lerobot" >&2',
                "  exit 12",
                "fi",
                f"exec python -m lerobot.scripts.train --policy {policy} --dataset {dataset}",
                "",
            ]
        )
        payload = EnginePayload(
            adapter=self.name,
            env_name=policy,
            command=["python", "-m", "lerobot.scripts.train", "--policy", policy],
            ignored_fields=ignored_scene_fields(spec, honors_scene=False),
            notes=[
                "LeRobot is the dataset and imitation backend. Not a new format.",
                f"Dataset: {dataset or '(none)'}",
            ],
            extra={"policy": policy, "datasets": datasets},
        )
        payload.files["engine_payload.json"] = json.dumps(payload.as_dict(), indent=2)
        payload.files["train_lerobot.sh"] = script
        return payload

    def launch(
        self,
        spec: dict[str, Any],
        payload: EnginePayload,
        run_dir: Path,
        log: LogFn,
    ) -> EvalResult:
        log("LeRobot launch is not enabled in this phase")
        raise AdapterUnavailable(
            "Imitation training is Phase 2. Inspect a LeRobot dataset in the Data room, "
            f"or run the generated train_lerobot.sh later. Files: {run_dir}"
        )
