from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from humanoid_training.adapters.base import EnginePayload, EvalResult, LogFn, Support
from humanoid_training.adapters.common import ignored_scene_fields, recipe_adapter_config
from humanoid_training.errors import AdapterUnavailable


class MJLabAdapter:
    """Compile an mjlab training command. Launch is Phase 3."""

    name = "mjlab"

    def support(self, spec: dict[str, Any]) -> Support:
        cfg = recipe_adapter_config(spec, self.name)
        if cfg.get("unsupported"):
            return Support(False, str(cfg["unsupported"]))
        if not cfg.get("task"):
            return Support(False, "recipe does not define adapters.mjlab.task")
        return Support(True)

    def compile(self, spec: dict[str, Any]) -> EnginePayload:
        cfg = recipe_adapter_config(spec, self.name)
        task = str(cfg["task"])
        train = spec.get("train") or {}
        seed = int(train.get("seed") or 1)
        script = "\n".join(
            [
                "#!/usr/bin/env bash",
                "set -euo pipefail",
                "# Generated by Humanoid Training. Requires: uvx --from mjlab ...",
                f"# task={task} seed={seed}",
                "if ! command -v train >/dev/null 2>&1; then",
                '  echo "mjlab is not on PATH. See https://github.com/mujocolab/mjlab" >&2',
                "  exit 12",
                "fi",
                f"exec python -m mjlab.scripts.train --task {task} --seed {seed}",
                "",
            ]
        )
        payload = EnginePayload(
            adapter=self.name,
            env_name=task,
            command=["python", "-m", "mjlab.scripts.train", "--task", task],
            ignored_fields=ignored_scene_fields(spec, honors_scene=False),
            notes=[
                "mjlab (Isaac Lab API on MuJoCo Warp). GPU recommended.",
                f"Task: {task}",
            ],
            extra={"task": task, "seed": seed},
        )
        payload.files["engine_payload.json"] = json.dumps(payload.as_dict(), indent=2)
        payload.files["train_mjlab.sh"] = script
        return payload

    def launch(
        self,
        spec: dict[str, Any],
        payload: EnginePayload,
        run_dir: Path,
        log: LogFn,
    ) -> EvalResult:
        log("mjlab launch is not enabled in this phase")
        raise AdapterUnavailable(
            "G1 reach / mjlab train is blocked on this CPU studio — not a silent failure. "
            "On a GPU box with mjlab installed, run the generated train_mjlab.sh. "
            "For a CPU preview use g1-stand (hold) or pick-and-place (mustard BC). "
            f"Compiled payload: {run_dir}"
        )
