from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from humanoid_training import hardware
from humanoid_training.adapters.base import EnginePayload, EvalResult, LogFn, Support
from humanoid_training.adapters.common import ignored_scene_fields, recipe_adapter_config
from humanoid_training.adapters.process import harvest_mp4, stream_process, write_job
from humanoid_training.errors import AdapterUnavailable

LOGDIR_NAME = "mjlab_logs"


def _hparams(spec: dict[str, Any], payload: EnginePayload | None = None) -> tuple[str, int, int, bool]:
    cfg = recipe_adapter_config(spec, "mjlab")
    extra = (payload.extra if payload else {}) or {}
    task = str((payload.env_name if payload else None) or cfg.get("task") or "")
    train = spec.get("train") or {}
    steps = int(train.get("steps") or extra.get("steps") or extra.get("max_iterations") or 100_000)
    seed = int(train.get("seed") or extra.get("seed") or 1)
    want_video = bool((spec.get("eval") or {}).get("record_video", True))
    return task, steps, seed, want_video


def _motion_registry(spec: dict[str, Any]) -> str | None:
    """WandB / HT_MJLAB_MOTION registry name for tracking tasks."""
    import os

    cfg = recipe_adapter_config(spec, "mjlab")
    for key in ("registry_name", "motion", "motion_registry"):
        raw = cfg.get(key)
        if raw:
            return str(raw).strip()
    data = (spec.get("data") or {}).get("motion") or (spec.get("data") or {}).get("registry")
    if data:
        return str(data).strip()
    for env_name in ("HT_MJLAB_MOTION", "WANDB_MOTION_REGISTRY"):
        raw = os.environ.get(env_name)
        if raw and raw.strip() and raw.strip().lower() not in {"0", "false", "no", "off"}:
            return raw.strip()
    return None


def mjlab_train_command(
    spec: dict[str, Any],
    *,
    payload: EnginePayload | None = None,
    logdir: str | Path = LOGDIR_NAME,
) -> list[str]:
    task, steps, seed, want_video = _hparams(spec, payload)
    extra = ["--log-root", str(logdir), "--agent.seed", str(seed), "--agent.max-iterations", str(steps)]
    if want_video:
        extra.extend(["--video", "True"])
    motion = _motion_registry(spec)
    if motion and "Tracking" in task:
        extra.extend(["--registry-name", motion])
    return hardware.mjlab_train_argv(task, extra)


class MJLabAdapter:
    """Compile and, on a GPU box with mjlab, launch a registered mjlab task."""

    name = "mjlab"

    def support(self, spec: dict[str, Any]) -> Support:
        cfg = recipe_adapter_config(spec, self.name)
        if cfg.get("unsupported"):
            return Support(False, str(cfg["unsupported"]))
        if not cfg.get("task"):
            return Support(False, "recipe does not define adapters.mjlab.task")
        return Support(True)

    def compile(self, spec: dict[str, Any]) -> EnginePayload:
        task, steps, seed, want_video = _hparams(spec)
        command = mjlab_train_command(spec, logdir=LOGDIR_NAME)
        # Portable script uses python -m even if this host resolved a fake CLI.
        portable = [
            "python",
            "-m",
            "mjlab.scripts.train",
            task,
            "--log-root",
            LOGDIR_NAME,
            "--agent.seed",
            str(seed),
            "--agent.max-iterations",
            str(steps),
        ]
        if want_video:
            portable.extend(["--video", "True"])
        script = "\n".join(
            [
                "#!/usr/bin/env bash",
                "set -euo pipefail",
                "# Generated by Humanoid Training. Requires mjlab + NVIDIA GPU.",
                f"# task={task} seed={seed} max_iterations={steps}",
                "if ! python -c 'import mjlab' >/dev/null 2>&1; then",
                '  echo "mjlab is not installed. See https://github.com/mujocolab/mjlab" >&2',
                "  echo \"Then: python -m mjlab.scripts.train " + task + " --video True\" >&2",
                "  exit 12",
                "fi",
                "exec " + " ".join(portable),
                "",
            ]
        )
        motion = _motion_registry(spec)
        notes = [
            "mjlab (Isaac Lab API on MuJoCo Warp). Needs an NVIDIA GPU.",
            f"Task: {task} (positional id for python -m mjlab.scripts.train).",
            "launch() runs that command when mjlab and a GPU are present.",
        ]
        if "Tracking" in task:
            if motion:
                notes.append(f"Motion registry: {motion}")
            else:
                notes.append(
                    "Motion tracking needs HT_MJLAB_MOTION=<wandb-org/motions/name> "
                    "(or adapters.mjlab.registry_name)."
                )
                notes.append(
                    "LAFAN1 G1 CSVs: hf:lvhaidong/LAFAN1_Retargeting_Dataset (g1/**). "
                    "Convert with mjlab.scripts.csv_to_npz (not Isaac NPZs), "
                    "then WandB registry. See ht datasets pins / GET /api/datasets/pins."
                )
        if motion and "Tracking" in task and "--registry-name" not in " ".join(portable):
            portable.extend(["--registry-name", motion])
        payload = EnginePayload(
            adapter=self.name,
            env_name=task,
            command=command,
            ignored_fields=ignored_scene_fields(spec, honors_scene=False),
            notes=notes,
            extra={
                "task": task,
                "seed": seed,
                "max_iterations": steps,
                "logdir": LOGDIR_NAME,
                "registry_name": motion,
            },
        )
        payload.files["engine_payload.json"] = json.dumps(payload.as_dict(), indent=2)
        # Rebuild script if motion flag was appended after the first join.
        if motion and "Tracking" in task:
            script = "\n".join(
                [
                    "#!/usr/bin/env bash",
                    "set -euo pipefail",
                    "# Generated by Humanoid Training. Requires mjlab + NVIDIA GPU.",
                    f"# task={task} seed={seed} max_iterations={steps} registry={motion}",
                    "if ! python -c 'import mjlab' >/dev/null 2>&1; then",
                    '  echo "mjlab is not installed. See https://github.com/mujocolab/mjlab" >&2',
                    "  exit 12",
                    "fi",
                    "exec " + " ".join(portable),
                    "",
                ]
            )
        payload.files["train_mjlab.sh"] = script
        return payload

    def launch(
        self,
        spec: dict[str, Any],
        payload: EnginePayload,
        run_dir: Path,
        log: LogFn,
    ) -> EvalResult:
        run_dir = Path(run_dir)
        log("checking for mjlab")
        if not hardware.mjlab_cli():
            raise AdapterUnavailable(
                "mjlab is not installed on this machine. "
                "This is expected on the CPU studio — not a silent failure. "
                "On a GPU box: pip/uv install mjlab, then "
                "ht train spec/examples/g1-walk.json with backend.prefer [mjlab]. "
                "For a CPU preview use g1-stand or pick-and-place. "
                f"Compiled payload: {run_dir}"
            )
        if not hardware.gpu_available():
            raise AdapterUnavailable(
                "mjlab train is blocked: no NVIDIA GPU. "
                "This is expected on the CPU studio — not a silent failure. "
                "On a GPU box with mjlab: ht train spec/examples/g1-walk.json "
                "(backend.prefer: [mjlab]). Or use g1-stand / pick-and-place here. "
                f"Compiled payload: {run_dir}"
            )
        task, _steps, _seed, _want = _hparams(spec, payload)
        if "Tracking" in task and not _motion_registry(spec):
            raise AdapterUnavailable(
                "mjlab motion tracking is blocked: set HT_MJLAB_MOTION="
                "<wandb-org/motions/name> (or adapters.mjlab.registry_name). "
                "See https://mujocolab.github.io/mjlab/main/source/training/motion_imitation.html "
                f"Compiled payload: {run_dir}"
            )
        logdir = run_dir / LOGDIR_NAME
        logdir.mkdir(parents=True, exist_ok=True)
        command = mjlab_train_command(spec, payload=payload, logdir=logdir)
        task, steps, seed, want_video = _hparams(spec, payload)
        log(" ".join(command))
        write_job(run_dir, {"command": command, "logdir": str(logdir), "task": task, "status": "starting"})
        rc = stream_process(
            command,
            run_dir,
            log,
            missing="Could not start mjlab. Install from https://github.com/mujocolab/mjlab",
        )
        write_job(
            run_dir,
            {
                "command": command,
                "logdir": str(logdir),
                "task": task,
                "returncode": rc,
                "status": "exited",
            },
        )
        facts: dict[str, Any] = {
            "kind": "rl",
            "engine": "mjlab",
            "device": "gpu",
            "env": task,
            "policy": "ppo",
            "seed": seed,
            "max_iterations": steps,
            "returncode": rc,
        }
        if rc != 0:
            log(f"mjlab exited {rc}; not harvesting a clip")
            return EvalResult(
                success_rate=0.0,
                mean_return=0.0,
                episodes=int((spec.get("eval") or {}).get("episodes") or 0),
                video_path=None,
                passed=False,
                notes=[f"mjlab exited {rc}. Not substituting a stand clip."],
                facts=facts,
            )
        dest = run_dir / "eval.mp4"
        video = harvest_mp4(logdir, dest) if want_video else None
        if want_video and video is None:
            raise AdapterUnavailable(
                "mjlab finished (exit 0) but wrote no *.mp4 under "
                f"{logdir}. Not substituting a stand clip. Run dir: {run_dir}"
            )
        notes = [
            f"mjlab PPO task={task} max_iterations={steps} seed={seed}",
            "Eval clip is the engine rollout, not an independent reach/upright score.",
        ]
        if video:
            notes.append(f"harvested {video.name} from mjlab_logs")
            log(f"harvested {video}")
        else:
            notes.append("record_video=false; no eval.mp4")
        return EvalResult(
            success_rate=1.0,
            mean_return=0.0,
            episodes=int((spec.get("eval") or {}).get("episodes") or 1),
            video_path=video,
            passed=True,
            notes=notes,
            facts=facts,
        )
