from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Any

from humanoid_training.adapters.base import EnginePayload, EvalResult, LogFn, Support
from humanoid_training.adapters.common import ignored_scene_fields, recipe_adapter_config
from humanoid_training.errors import AdapterUnavailable


PLAYGROUND_ENV = "G1JoystickFlatTerrain"


class PlaygroundAdapter:
    """Compile to MuJoCo Playground. Launch only if the package is installed."""

    name = "playground"

    def support(self, spec: dict[str, Any]) -> Support:
        cfg = recipe_adapter_config(spec, self.name)
        if cfg.get("unsupported"):
            return Support(False, str(cfg["unsupported"]))
        if not cfg.get("env_name"):
            return Support(False, "recipe does not define adapters.playground.env_name")
        return Support(True)

    def compile(self, spec: dict[str, Any]) -> EnginePayload:
        cfg = recipe_adapter_config(spec, self.name)
        env_name = str(cfg.get("env_name") or PLAYGROUND_ENV)
        train = spec.get("train") or {}
        steps = int(train.get("steps") or 100_000)
        seed = int(train.get("seed") or 1)
        command = list(
            cfg.get("train_command")
            or [
                "train-jax-ppo",
                "--env_name",
                env_name,
            ]
        )
        script = "\n".join(
            [
                "#!/usr/bin/env bash",
                "set -euo pipefail",
                "# Generated by Humanoid Training. Requires: pip install playground",
                f"# env={env_name} seed={seed} steps={steps}",
                "if ! command -v train-jax-ppo >/dev/null 2>&1; then",
                '  echo "MuJoCo Playground is not on PATH. Install with: pip install playground" >&2',
                "  exit 12",
                "fi",
                "exec " + " ".join(command),
                "",
            ]
        )
        payload = EnginePayload(
            adapter=self.name,
            env_name=env_name,
            command=command,
            ignored_fields=ignored_scene_fields(spec, honors_scene=False),
            notes=[
                "MuJoCo Playground / MJX. Needs an NVIDIA GPU for a real G1 train.",
                "This adapter compiles the spec; launch() refuses unless playground is installed.",
            ],
            extra={"steps": steps, "seed": seed},
        )
        payload.files["engine_payload.json"] = json.dumps(payload.as_dict(), indent=2)
        payload.files["train.sh"] = script
        return payload

    def launch(
        self,
        spec: dict[str, Any],
        payload: EnginePayload,
        run_dir: Path,
        log: LogFn,
    ) -> EvalResult:
        log("checking for MuJoCo Playground")
        if shutil.which("train-jax-ppo") is None:
            try:
                import mujoco_playground  # noqa: F401
            except ImportError:
                raise AdapterUnavailable(
                    "G1 walk is compiled, but MuJoCo Playground is not installed "
                    "in this environment. On a machine with an NVIDIA GPU:\n"
                    "  pip install playground\n"
                    "  train-jax-ppo --env_name G1JoystickFlatTerrain\n"
                    f"Generated files are in {run_dir}"
                ) from None
        raise AdapterUnavailable(
            "Playground is present, but live G1 training is Phase 1/3 work "
            f"(GPU job runner). Payload is in {run_dir}. "
            "Run the generated train.sh on a GPU box."
        )
